<a href="https://colab.research.google.com/github/douglaseaf15/Numpy-Python/blob/master/Criar_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Create arrays

In [0]:
import numpy as np

In [11]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? y


# Create ndarrays from lists. note: every element must be the same type (will be converted if possible)


In [0]:
data1 = [1, 2, 3, 4, 5] # list


In [0]:
arr1 = np.array(data1) # 1d array


In [0]:
data2 = [range(1, 5), range(5, 9)] # list of lists


In [0]:
arr2 = np.array(data2) # 2d array


In [0]:
arr3  = arr2.tolist() # convert array back to list

#create special arrays

In [24]:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros((3, 6))


array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [26]:
np.ones(10)


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [27]:
np.linspace(0, 1, 5) # 0 to 1 (inclusive) with 5 points


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [30]:
np.logspace(0, 3, 4) # 10^0 to 10^3 (inclusive) with 4 points

array([   1.,   10.,  100., 1000.])

# arange is like range, except it returns an array (not a list)

In [0]:
int_array = np.arange(5)


In [0]:
float_array = int_array.astype(float)
